name: Pipeline

on:
  pull_request:
    branches: [ master ]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Empacotamento do projeto
        run: mvn -B clean package -DskipTests

  format:
    name: Format
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
        with:
        ref: ${{github.event.pull_request.head.ref}}
        fetch-depth: 0
        token: ${{secrets.GITHUB_TOKEN}}
      
      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Run spotless:apply
        run: ./mvnw spotless:apply

      - name: Commit and push spotless changes
        run: |
          git config user.name github-actions-format
          git add .
          git diff --quiet --exit-code || git commit -m "Apply spotless formatting" || echo "No changes needed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Testes Unitários
        run: mvn -B verify

      - name: Upload do relátório do JaCoCo
        uses: actions/upload-artifact@v5.0.0
        with:
          name: jacoco-report
          path: target/site/jacoco
