name: Pipeline

on:
  pull_request:
    branches: [master]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    if: |
      github.actor != 'github-actions[bot]' &&
      !contains(github.event.pull_request.title, 'spotless')
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: 25

      - name: Empacotamento do projeto
        run: mvn -B clean package -DskipTests

  tests:
    if: |
      github.actor != 'github-actions[bot]' &&
      !contains(github.event.pull_request.title, 'spotless')
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Instalar Java 25
        uses: actions/setup-java@v5.0.0
        with:
          distribution: "temurin"
          java-version: 25

      - name: Testes Unitários
        run: mvn -B verify

      - name: Upload do relatório do JaCoCo
        uses: actions/upload-artifact@v5.0.0
        with:
          name: jacoco-report
          path: target/site/jacoco

  bot-pass:
    if: github.actor == 'github-actions[bot]'
    name: CI ignorada (bot commit)
    runs-on: ubuntu-latest

    steps:
      - run: echo "Commit automático do Spotless — CI ignorada"